export const categories = [
  { name: "Bill", icon: "receipt_long" },
  { name: "Car", icon: "directions_car" },
  { name: "Clothing", icon: "styler" },
  { name: "Education", icon: "school" },
  { name: "Entertainment", icon: "confirmation_number" },
  { name: "Food", icon: "restaurant" },
  { name: "Health", icon: "ecg_heart" },
  { name: "Home", icon: "house" },
  { name: "Insurance", icon: "health_and_safety" },
  { name: "Shopping", icon: "shopping_cart" },
  { name: "Tax", icon: "account_balance" },
  { name: "Phone", icon: "phone_iphone" },
  { name: "Transport", icon: "commute" },
  { name: "Other", icon: "category" },
  { isIncome: true, name: "Grants", icon: "redeem" },
  { isIncome: true, name: "Refund", icon: "currency_exchange" },
  { isIncome: true, name: "Rental", icon: "real_estate_agent" },
  { isIncome: true, name: "Salary", icon: "add_card" },
  { isIncome: true, name: "Sale", icon: "sell" },
  { isIncome: true, name: "Other", icon: "category" },
];

export const allColors = [
  "#ff8811",
  "#f3de2c",
  "#7cb518",
  "#5c8001",
  "#fbb02d",
  "#f94144",
  "#f3722c",
  "#f8961e",
  "#f9844a",
  "#f9c74f",
  "#90be6d",
  "#43aa8b",
  "#4d908e",
  "#577590",
  "#277da1",
];

export const categoriesIcon = [
  "category",
  "receipt_long",
  "directions_car",
  "styler",
  "school",
  "confirmation_number",
  "restaurant",
  "ecg_heart",
  "house",
  "health_and_safety",
  "shopping_cart",
  "account_balance",
  "phone_iphone",
  "commute",
  "redeem",
  "currency_exchange",
  "real_estate_agent",
  "add_card",
  "sell",
];
